Tag Prefix 2nd Try
flavio/fresh-container pull request #4
Opened 2021-10-20 04:05 UTC by patricegautier

Hi Flavio,

Thanks for the detailed feedback.   All of it made great sense..

I think I caught everything in this new pull request, and added a couple of test cases as well.

Let me know!

2021-10-20 06:52 UTC, flavio requested changes
Hi, thanks for the fixes you've made.

I've left some comments, please do not open a new PR, but rather send the fixes as new commits into this PR.

You can then squash everything into a single commit as a last step, once I've approved all the changes.

Please, configure your IDE/editor to run gofmt on save, there are many small things that could be fixed by it.

2021-10-20 06:52 UTC, flavio commented on internal/cmd/check.go
> +				evaluation.Image, evaluation.Constraint, evaluation.TagPrefix)
I would do something like that:
```go
msg := fmt.Sprintf(
   "%s is already the latest version available that satisfies the %s constraint", 
   evaluation.Image,
   evaluation.Constraint)
if evaluation.TagPrefix != "" {
   msg = fmt.Sprintf("%s and the tag prefix %s", msg, evaluation.TagPrefix)
}
fmt.Println(msg)
```

2021-10-20 06:52 UTC, flavio commented on internal/cmd/check.go
> +func localEvaluation(image, constraint, tagPrefix string, configFile string, ctx context.Context) (evaluation fresh_container.ImageUpgradeEvaluationResponse, err error) {
remove the `string` type from here, you can inherit the one from `configFile`

2021-10-20 06:52 UTC, flavio commented on internal/cmd/check.go
> +func remoteEvaluation(server, image, constraint string, tagPrefix string, showProgress bool) (evaluation fresh_container.ImageUpgradeEvaluationResponse, err error) {
Same here, but this time remove the `string` type from the left

2021-10-20 06:52 UTC, flavio commented on internal/workers/job_handler.go
> +func (w *BackgroundWorker) ProcessJob(ctx context.Context, id, img, constraint string, tagPrefix string) error {
remove the `string` type from the left

2021-10-20 06:52 UTC, flavio commented on pkg/fresh_container/client.go
> +func (c *Client) EvalUpgrade(image, constraint string, tagPrefix string) (RemoteEvaluationResponse, error) {
remove the `string` type from the left

2021-10-20 06:52 UTC, flavio commented on pkg/fresh_container/comparer.go
> +func NextTag(curTag, constraint string, tagPrefix string, tags []string) (string, error) {
remove the string type on the left

2021-10-20 06:52 UTC, flavio commented on pkg/fresh_container/comparer.go
> +	trimmedTag:=strings.TrimPrefix(curTag, tagPrefix)
please run gofmt against all the files you changed, there are other similar issues around

2021-10-20 06:52 UTC, flavio commented on pkg/fresh_container/image.go
> +func NewImage(image string, tagPrefix string) (Image, error) {
remove the string type from the left

2021-10-20 06:52 UTC, flavio commented on pkg/fresh_container/image.go
> +
remove the empty line

2021-10-20 06:52 UTC, flavio commented on pkg/fresh_container/tags.go
> +
remove the empty line

2021-10-20 06:52 UTC, flavio commented on pkg/fresh_container/tags.go
> +func TagsToVersions(tags []string, tagPrefix string, skipInvalid bool) (versions semver.Versions, err error) {
I think this new implementation is overly complicated, I would just do:

```golang
func TagsToVersions(tags []string, tagPrefix string, skipInvalid bool) (versions semver.Versions, err error) {
   for _, tag := range tags {
                tag = strings.TrimPrefix(tag, tagPrefix)
		v, err := semver.Parse(tag)
		if err == nil {
			versions = append(versions, v)
		} else if skipInvalid {
			log.WithFields(log.Fields{
				"tag":   tag,
                                "tagPrefix": tagPrefix,
				"error": err}).Warn("Skipping image tag")
		} else {
			return semver.Versions{}, err
		}
	}

	return versions, nil
}
```

2021-10-20 19:51 UTC, patricegautier commented on pkg/fresh_container/tags.go
> +func TagsToVersions(tags []string, tagPrefix string, skipInvalid bool) (versions semver.Versions, err error) {
indeed.

2021-10-20 20:03 UTC, patricegautier commented
Thanks again for the great feedback. 

Take a look I think it's close.

2021-10-21 05:17 UTC, patricegautier commented
Well hang on - the server case needs work too..

2021-10-21 06:31 UTC, patricegautier commented
I had to bang my head on bit on gorilla/mux but it works now..

2021-10-21 07:23 UTC, flavio requested changes
Yes, this looks definitely better :clap: 

You still have to fix the background job definition, as you pointed out. I'm looking forward to see the last fix :)

2021-10-21 07:26 UTC, flavio commented on cmd/fresh-container/main.go
> +						Usage:   "Tag Prefix: use if the version tags from the repository have a prefix before the versioning infomation, i.e for Ubuntu-2021.10.3 use Ubuntu- as a tag prefix.  Only tags starting with
~~Not really, the code has been changed so that it processes all the tags, regardless of the prefix they use. If they have a prefix that matches the one provided here, this will be stripped~~

Sorry, I didn't read the code later on. What you stated is correct

2021-10-21 07:53 UTC, flavio requested changes
Last round of changes. Please run `gofmt`, otherwise the next time someone with `gofmt` enabled changes one of these files he will get a list of unrelated changes

2021-10-21 07:53 UTC, flavio commented on internal/api/v1/check.go
> +		"tagPrefix": vars["tagPrefix"],
You should really automate `gofmt` ;)

2021-10-21 07:53 UTC, flavio commented on internal/api/v1/server.go
> +
nitpicking, remove the empty line

2021-10-21 07:53 UTC, flavio commented on internal/api/v1/server.go
> +	// Registering the handler twice seems to be the easiest way to have an option query
Yeah, that looks like the only solution... I did some research too :(

2021-10-21 19:30 UTC, patricegautier commented on internal/api/v1/check.go
> +		"tagPrefix": vars["tagPrefix"],
grrr I thought I had

2021-10-21 19:32 UTC, patricegautier commented on internal/api/v1/server.go
> +	// Registering the handler twice seems to be the easiest way to have an option query
I could see this being a real pain if you need a few optional query values.. 2^n handlers!

2021-10-21 19:35 UTC, patricegautier commented on internal/api/v1/check.go
> +		"tagPrefix": vars["tagPrefix"],
Ok I see the problem - I missed a set of directories when I set it up..

2021-10-21 19:47 UTC, patricegautier commented
The background job to build the container on the GitHub side is failing.  I am going to need some help to get unblocked here I think:

https://github.com/patricegautier/fresh-container/runs/3968310010?check_suite_focus=true

it's failing with:

#30 exporting to image
483
#30 pushing layers 0.9s done
484
#30 ERROR: unexpected status: 403 Forbidden
485
------
486
 > exporting to image:
487
------
488
error: failed to solve: unexpected status: 403 Forbidden
489
Error: buildx failed with: error: failed to solve: unexpected status: 403 Forbidden

EDIT:  Looks like it might be a resource problem:  https://github.com/docker/build-push-action/issues/238

2021-10-22 03:48 UTC, patricegautier commented
There's a permission problem of some sort preventing the build of the container from succeeding, having to do with the image workflow.  I tried tweaking container-image.yml but that's not enough..

2021-10-22 03:49 UTC, patricegautier commented
also, it seems that having a hard-coded reference to the Flavio/fresh-container tag in gets in the way of forking.. There's probably a variable to solve that too.

2021-10-22 07:00 UTC, flavio requested changes
LGTM.

Before I can merging it, please do the following actions:

  * Remove the changes to the GitHub Action file, we will tackle that with another PR
  * Squash all the commits together, then force push. If you don't know how to do that I can help

Thanks again for your contribution

2021-10-22 07:00 UTC, flavio commented on .github/workflows/container-image.yml
> +            ghcr.io/pgautier/fresh-container:latest
Let's leave this change out of this PR, it's unrelated

2021-10-22 07:00 UTC, flavio commented on .github/workflows/container-image.yml
> +            ghcr.io/pgautier/fresh-container:${{ env.TAG_NAME }}
same here

2021-10-22 07:11 UTC, flavio commented
JFYI: I fixed the GitHub issue with https://github.com/flavio/fresh-container/commit/59a14bba5db76cba73158559db00f6a136331f1e, it's already inside of the `main` branch

2021-10-22 07:16 UTC, patricegautier commented
Ok I reverted the container name change in container-image.yml

I do need instructions on how to squash and force-push though..

2021-10-22 07:43 UTC, flavio commented
Oh, no worries about the squash and merge. I see GH added an option for doing that on my side (as someone who has merge rights). I'll handle that

2021-10-22 07:44 UTC, merged

2021-10-22 07:47 UTC, flavio commented
I've merged everything as you can see, I'll release a new version in the next days

2021-10-22 07:49 UTC, patricegautier commented
Great, thank you!

Sent from my iPad

> On Oct 22, 2021, at 12:47 AM, Flavio Castelli ***@***.***> wrote:
> 
> ﻿
> I've merged everything as you can see, I'll release a new version in the next days
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.